const words = [
  "account",
  "advertisement",
  "competition",
  "destruction",
  "comparison",
  "invention",
  "knowledge",
  "daughter",
  "development",
  "experience",
  "frequent",
  "government",
  "history",
  "interest",
  "iron",
  "steel",
  "language",
  "library",
  "memory",
  "necessary",
  "observation",
  "organization",
  "physical",
  "private",
  "yesterday",
  "wise",
  "wing",
  "expert",
  "family",
  "healthy",
];

export default words;
